server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flower_catalog?serverTimeZone=ADT
    username: postgres
    password: 123456
  jpa:
    spring.jpa.properties.hibernate.default_schema: my_schema
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
